import './globals.css'
import type { Metadata } from 'next'
import { VT323, Poppins } from 'next/font/google'

const vt323 = VT323({
    weight: '400',
    subsets: ['latin'],
    variable: "--font-vt323",
})

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--font-poppins",
})  

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${vt323.variable}, ${poppins.variable} font-poppins`}>{children}</body>
    </html>
  )
}
